export const blogList = [
  {
    id: 1,
    title: "Supra",
    category: "спорт кар",
    subCategory: ["гонки", "Япония", "дрифт"],
    description:
      "Под капотом Супры скрывается мощный двигатель, обычно с шестицилиндровой конфигурацией, который обеспечивает впечатляющую скорость и динамику.",
    authorName: "Никита Булынкин",
    authorAvatar: "https://sun9-9.userapi.com/impg/88VeXpQ-n5tDhb0A3c_sGFOJ96_-YMMsZ1-Qsw/OyDUTVHKrbg.jpg?size=960x1280&quality=95&sign=d5eb425141c5eeef436cd32b6fd6147a&type=album",
    createdAt: "Май 18",
    cover: "https://www.svarz.com/wp-content/uploads/2021/03/this-toyota-supra-has-more-power-than-a-bugatti-veyron.jpg",
  },
  {
    id: 2,
    title: "Ferrari 488 GTB",
    category: "спорт кар",
    subCategory: ["гонки", "Италия", "турбонаддув"],
    description:
      "Ferrari 488 GTB - это эмблематический спортивный автомобиль, который сочетает в себе элегантный дизайн и высокую производительность. Он оснащен мощным турбированным двигателем, который позволяет ему разгоняться до впечатляющих скоростей.",
    authorName: "Никита Булынкин",
    authorAvatar: "https://sun9-9.userapi.com/impg/88VeXpQ-n5tDhb0A3c_sGFOJ96_-YMMsZ1-Qsw/OyDUTVHKrbg.jpg?size=960x1280&quality=95&sign=d5eb425141c5eeef436cd32b6fd6147a&type=album",
    createdAt: "Май 18",
    cover: "https://carsdb.ru/auto/ferrari/488_gtb/photo/9.jpg",
  },
  {
    id: 3,
    title: "Tesla Model S",
    category: "электромобиль",
    subCategory: ["экология", "технологии", "автопилот"],
    description:
      "Tesla Model S - это революционный электромобиль, который сочетает в себе элегантный дизайн, превосходную эффективность и передовые технологии. Он предлагает дальность хода, доступную только для электромобилей, и оснащен передовой системой автопилота.",
    authorName: "Никита Булынкин",
    authorAvatar: "https://sun9-9.userapi.com/impg/88VeXpQ-n5tDhb0A3c_sGFOJ96_-YMMsZ1-Qsw/OyDUTVHKrbg.jpg?size=960x1280&quality=95&sign=d5eb425141c5eeef436cd32b6fd6147a&type=album",
    createdAt: "Май 18",
    cover: "https://lh6.googleusercontent.com/proxy/YIDx3hvY_LLQfCIzUNgAIrEOWoidbf1RMcKObSHY2H_5HOnrGBxpYJnwowsH0DZAwQgvYcfpRFHr3x-0fwoJr8v4A6NSceVj98_FNoFMET1IVXKi4ZFG7WOGm53oFX_u9qwly6LDEd8=s0-d",
  },
  {
    id: 4,
    title: "Porsche 911",
    category: "спорт кар",
    subCategory: ["гонки", "Германия", "престиж"],
    description:
      "Porsche 911 - это икона среди спортивных автомобилей. Своим характерным внешним видом и непревзойденными характеристиками, он обеспечивает захватывающие ощущения и мощную производительность на дороге.",
    authorName: "Никита Булынкин",
    authorAvatar: "https://sun9-9.userapi.com/impg/88VeXpQ-n5tDhb0A3c_sGFOJ96_-YMMsZ1-Qsw/OyDUTVHKrbg.jpg?size=960x1280&quality=95&sign=d5eb425141c5eeef436cd32b6fd6147a&type=album",
    createdAt: "Май 18",
    cover: "https://i.ytimg.com/vi/lEk1tUD14HM/maxresdefault.jpg",
  },
  {
    id: 5,
    title: "Audi R8",
    category: "спорт кар",
    subCategory: ["гонки", "Германия", "престиж"],
    description:
      "Audi R8 - это спортивный автомобиль с выдающимися характеристиками и элегантным стилем. Он оснащен мощным двигателем и передовыми технологиями, которые делают его одним из самых желанных автомобилей в своем классе.",
    authorName: "Никита Булынкин",
    authorAvatar: "https://sun9-9.userapi.com/impg/88VeXpQ-n5tDhb0A3c_sGFOJ96_-YMMsZ1-Qsw/OyDUTVHKrbg.jpg?size=960x1280&quality=95&sign=d5eb425141c5eeef436cd32b6fd6147a&type=album",
    createdAt: "Май 18",
    cover: "https://s1.1zoom.ru/big0/570/Audi_R8_V10_performance_Spyder_2020_Grey_Metallic_596606_1280x853.jpg",
  },
  {
    id: 6,
    title: "Chevrolet Corvette",
    category: "спорт кар",
    subCategory: ["гонки", "США", "мощность"],
    description:
      "Chevrolet Corvette - это американская икона, которая славится своей мощностью и динамикой. С его эффектным дизайном и производительным двигателем, Corvette предлагает непревзойденные ощущения от вождения.",
    authorName: "Никита Булынкин",
    authorAvatar: "https://sun9-9.userapi.com/impg/88VeXpQ-n5tDhb0A3c_sGFOJ96_-YMMsZ1-Qsw/OyDUTVHKrbg.jpg?size=960x1280&quality=95&sign=d5eb425141c5eeef436cd32b6fd6147a&type=album",
    createdAt: "Май 18",
    cover: "https://proaveo.ru/wp-content/uploads/b/b/9/bb9ed4bcb311d9154d65a4c43f8a9a9b.jpeg",
  },
  {
    id: 7,
    title: "Mercedes-Benz S-Class",
    category: "люксовый автомобиль",
    subCategory: ["комфорт", "престиж", "технологии"],
    description:
      "Mercedes-Benz S-Class - это вершина роскоши и комфорта в мире автомобилей. Своим изысканным дизайном, роскошным интерьером и передовыми технологиями, S-Class устанавливает новые стандарты в сегменте люксовых автомобилей.",
    authorName: "Никита Булынкин",
    authorAvatar: "https://sun9-9.userapi.com/impg/88VeXpQ-n5tDhb0A3c_sGFOJ96_-YMMsZ1-Qsw/OyDUTVHKrbg.jpg?size=960x1280&quality=95&sign=d5eb425141c5eeef436cd32b6fd6147a&type=album",
    createdAt: "Май 18",
    cover: "https://www.premiumfelgi.com/modGalerie/en_GB/2084/4Gallery/2084_Wheels-Mercedes-S-klasa-S63-65-AMG-W222.jpg",
  },
  {
    id: 8,
    title: "BMW M5",
    category: "спорт седан",
    subCategory: ["гонки", "Германия", "производительность"],
    description:
      "BMW M5 - это спортивный седан, который сочетает в себе элегантность и производительность. С его мощным двигателем и передовыми технологиями, M5 предлагает удивительные возможности для вождения как на трассе, так и на городских улицах.",
    authorName: "Никита Булынкин",
    authorAvatar: "https://sun9-9.userapi.com/impg/88VeXpQ-n5tDhb0A3c_sGFOJ96_-YMMsZ1-Qsw/OyDUTVHKrbg.jpg?size=960x1280&quality=95&sign=d5eb425141c5eeef436cd32b6fd6147a&type=album",
    createdAt: "Май 18",
    cover: "https://kurs.com.ua/uploads/monthly_2020_06/d4f53tol4o_big.jpg.b4207ed60965b11342d74026f81366ad.jpg",
  },
  {
    id: 9,
    title: "Ford Mustang",
    category: "мускул-кар",
    subCategory: ["американские автомобили", "классика", "мощность"],
    description:
      "Ford Mustang - это символ американской автомобильной культуры. С его иконическим дизайном и мощным двигателем, Mustang обещает незабываемые ощущения от вождения и невероятную мощность на дороге.",
    authorName: "Никита Булынкин",
    authorAvatar: "https://sun9-9.userapi.com/impg/88VeXpQ-n5tDhb0A3c_sGFOJ96_-YMMsZ1-Qsw/OyDUTVHKrbg.jpg?size=960x1280&quality=95&sign=d5eb425141c5eeef436cd32b6fd6147a&type=album",
    createdAt: "Май 18",
    cover: "https://mobimg.b-cdn.net/v3/fetch/59/59b0dfc24ab958f46a65e0257f783087.jpeg",
  },
];
